### ISSUE TITLE
Database Schema

### ISSUE THREAD

**Issue by dndesai** [Rushi-Bhatt/SE17-Team-K#12]
1. Figure out how to store multiple values in a cell.
2. Create mapping tables for all drop downs.
3. Try to optimize feedback table.
![whatsapp image 2017-02-19 at 10 54 35 pm](https://cloud.githubusercontent.com/assets/21146384/23111439/9b92e548-f6f6-11e6-81ad-5ff906ca8159.jpeg)

**Comment by popoosl** [comment]
How about combining course and class to one table?
The only thing is to remove is the "semester" field. 
I can understand your initial thoughts of this field. If you add this field, it means you identify the same course of different semester as different sections. But there some drawbacks to do this. The admins have to add courses every semester to fill this table. Actually there are little possibility of changing. Moreover, this field is not so useful for users to search because it will add complexity to reach the results. As a user, I only care about the match of course and professor, it doesn't matter what the semester is. The timestamp in feedback table could provide more information than the semester field.
My idea is, there is no need to filter class by time (very little changes from this fall to that fall). Hence, we can combine the course table and class (section) table into one. The key is course ID + professor ID which is more simple to use.

**Comment by popoosl** [comment]
One more question, the reviews table is for the forum, am I correct?

**Comment by popoosl** [comment]
@Rushi-Bhatt :
I have deleted "section" table and "semester" field.  Currently, in course table, "number" is previous "section_id" (eg: CSC510), "professor_id" is previous "prof_id". I have updated your code accordingly. Hope it helps. 
I regenerated "review" model according to relationships with user and course (create a reference). Building relationship in models will bring convenience while developing, if you want, we can also do that for the feedback table and prof_rating table.
